Categories on homepage to improve usability
justnorris/easy-photography-portfolio pull request #13
Opened 2020-02-18 16:53 UTC by Ditger

2020-03-02 16:14 UTC, pyronaur requested changes
Thanks for the PR!
I didn't know I had that many typos in here 😅 !

I've left some feedback inline.

In addition - I think that this change shouldn't go out to all 10'000 sites that are already using Easy Photography Portfolio. Instead - I think this should be an option feature that's off by default so that updating the plugin doesn't cause unexpected changes.

Thanks again for the PR, I appreciate it!

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +        <span>Categories: </span>
I think this should be translatable

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +         foreach  (get_terms( 'phort_post_category' ) as $taxonomy) {
What if there are no terms? This'll show just `Categories: `?

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +<h1><?php echo phort_get_archive_title()?></h1>
Why `echo phort_get_archive_title()` instead of `phort_the_archive_title` ?

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +<h1><?php echo phort_get_archive_title()?></h1>
Is this really necessary for all instances of Easy Photography Portfolio plugin?

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +<h1><?php echo phort_get_archive_title()?></h1>
Is `h1` the most SEO friendly tag to use here?

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +             echo '<a href="' . get_category_link($taxonomy->term_id) . '">' . $terms[ (int) $taxonomy->term_id ] = esc_html( $taxonomy->name ) . ' ' . '</a>';
All URLs should be escaped with `esc_url()`

2020-03-02 16:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +             echo '<a href="' . get_category_link($taxonomy->term_id) . '">' . $terms[ (int) $taxonomy->term_id ] = esc_html( $taxonomy->name ) . ' ' . '</a>';
What does `$terms[ (int) $taxonomy->term_id ] = esc_html( $taxonomy->name )` do? It seems like it's assigning the taxonomy name value on the fly to `$terms[ (int) $taxonomy->term_id ]`.

Perhaps this should stick with the surrounding code style and avoid complex `echo` statements. Instead - prepare the data firsthand, and then render prepared data.

2020-03-03 10:14 UTC, Ditger commented on public/templates/archive/layout.php
> +        <span>Categories: </span>
I'll add that to the changes

2020-03-03 10:15 UTC, Ditger commented on public/templates/archive/layout.php
> +         foreach  (get_terms( 'phort_post_category' ) as $taxonomy) {
This does need a checker, since it'll just output Categories, will be added

2020-03-03 10:15 UTC, Ditger commented on public/templates/archive/layout.php
> +<h1><?php echo phort_get_archive_title()?></h1>
Otherwise it wouldn't display the title, but apparently it's not needed since it's a setting already, something I didn't notice before

2020-03-03 11:02 UTC, Ditger commented
The changes have been made, although I'll look into how this can become a on off setting with off as default

2020-03-04 12:03 UTC, pyronaur commented on public/templates/archive/layout.php
> +<h1><?php echo phort_get_archive_title()?></h1>
The 2 functions are different from one and the other, one is `phort_get_archive_title` and the other is `phort_the_archive_title` to mimic the native `get_the_title()` and `the_title()` functions.

2020-03-04 12:05 UTC, pyronaur commented
Can you check and make sure the coding standards match WordPress standards too? https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

2020-03-05 14:56 UTC, pyronaur commented
Hey @Ditger - let me know when this is ready for re-review!

2020-03-05 15:30 UTC, Ditger commented
It can be re-reviewed, normally it should be okay with the WordPress standards, let me know if there are things that need to be changed or improved.

2020-03-06 09:23 UTC, pyronaur requested changes
Looking good! I've left a few more suggestions, but I think we're almost done. When you're done - let me know and I'll apply the patch locally and test the design out as well.

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +                 	    echo '<span>' . esc_html('Categories: ') . '</span>';
To make this translatable, it needs to use an i18n function: https://developer.wordpress.org/themes/functionality/internationalization/

In this case, something like:

```
esc_html_e('Categories:', 'photography-portfolio')
```

(`photography-portfolio` is the text domain for this plugin, can be looked up here: https://github.com/pyronaur/easy-photography-portfolio/blob/master/photography-portfolio.php#L15 )

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +				         foreach  (get_terms( 'phort_post_category' ) as $taxonomy) {
Spaces are important for consistency. In this case, there are 2 spaces after `foreach` and no spaces within parenthesis. With Coding standards applied, this line would look like this:

```php
foreach ( get_terms( 'phort_post_category' ) as $taxonomy ) {
```

There are a few more spacing inconsistencies throughout this PR.

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +		            <span>No Categories found or categories are empty!</span>
This too should be internationalized. `esc_html_e()` can be used once more.

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +	         <?php if (phort_get_option( 'archive_category' ) !== 'disable'): ?>
Should the two empty div tags above be rendered if this option is disabled?

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +	         <?php if (phort_get_option( 'archive_category' ) !== 'disable'): ?>
Perhaps this should check for a positive condition rather than a negative one? So instead of  `$feature !== 'disable'` check for `$feature === 'enable'`. That's just a minor code style suggestion, feel free to ignore.

2020-03-06 09:23 UTC, pyronaur commented on public/templates/archive/layout.php
> +		            <span>No Categories found or categories are empty!</span>
Should the site visitor be notified that categories aren't found or are empty?
Is this useful information for them when viewing a portfolio? 

I haven't seen how this feature looks on a live site yet, but if it appears just as a blank string of text on top of the portfolio, maybe it's not necessary?

2020-03-06 09:23 UTC, pyronaur commented on Photography_Portfolio/Settings/General_Portfolio_Settings.php
> +		    'id'      => "archive_category",
Single quotes should be used for values not containing variables. Just to keep the consistency :)

2020-03-06 09:46 UTC, Ditger commented
All requested changes have been applied, normally all inconsistencies are resolved, let me know when I forgot one :)

2020-03-06 10:25 UTC, pyronaur requested changes

2020-03-06 10:25 UTC, pyronaur commented on public/templates/archive/layout.php
> +		         <?php if (count( get_terms('phort_post_category' ) ) !== 0 ): ?>
Missing a space :)

2020-03-06 10:25 UTC, pyronaur commented on public/templates/archive/layout.php
> +                 	    echo '<span>' . esc_html_e('Categories:', 'photography-portfolio') . '</span>';
`esc_html_e` stands for `echo esc_html__`, so it's a double-echo here.

Maybe do something like this instead?

```php
?>

<span>
    <?php esc_html_e( 'Categories:', 'photography-portfolio' ); ?>
</span>

<?php
```

2020-03-06 10:25 UTC, pyronaur commented on public/templates/archive/layout.php
> +		            <span><?php esc_html_e('No Categories found or categories are empty!', 'photography-portfolio') ?></span>
Missing spaces, - and I'm still curious about the thought process and whether this is necessary at all (see previous comment).

2020-03-06 10:25 UTC, pyronaur commented on public/templates/archive/layout.php
> +<?php if (phort_get_option( 'archive_category' ) === 'enable'): ?>
Missing spaces in parenthesis.

2020-03-06 10:25 UTC, pyronaur commented on public/templates/archive/layout.php
> +                 	    echo '<span>' . esc_html_e('Categories:', 'photography-portfolio') . '</span>';
Missing spaces in parenthesis.

2020-03-06 11:15 UTC, Ditger commented
Should be resolved now, the else statement was initially for testing, but is indeed not necessary in the final build.

2020-03-06 13:17 UTC, pyronaur commented on public/templates/archive/layout.php
> +					         echo '<a href="' . esc_url( get_category_link( $taxonomy->term_id ) ) . '">' . esc_html( $taxonomy->name ) . ' ' . '</a>';
One more improvement that I think could be made here would be to remove the "echo" here as well - to keep it the same as the rest of the file.

2020-03-06 13:18 UTC, pyronaur commented
Thanks for working on this! I'll give it a spin over the weekend and see how it looks and works.

2020-03-06 14:49 UTC, Ditger commented
It was a great experience to work on this, and with the last changes, the foreach is now more consistent like the rest, and also the links are fully operational.

2020-03-07 22:14 UTC, pyronaur requested changes

2020-03-07 22:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +                         <a href="<?php echo esc_url( get_category_link( $taxonomy->term_id ) ) ?>">
Missing semicolon :)

2020-03-07 22:14 UTC, pyronaur commented on public/templates/archive/layout.php
> +                             <?php esc_html_e( $taxonomy->name, 'photography-portfolio' ) ?>
Missing semicolon

2020-03-07 23:30 UTC, Ditger commented
Should be fixed now, didn't notice those, thanks for letting me know :)

2020-03-10 11:26 UTC, pyronaur commented on public/templates/archive/layout.php
> +                             <?php esc_html_e( $taxonomy->name, 'photography-portfolio' ); ?>
Didn't notice this before - Only text strings can be translated. `esc_html` and `esc_html__`(`esc_html_e`) are different  - `esc_html()` just escapes any content you pass to it, while `esc_html_*` functions escape a translatable text string and expects text, not a variable as they are used to generate translation files.

So here - I'd recommend just `echo esc_html( $taxonomy->name );`.

2020-03-10 14:20 UTC, Ditger commented
Changes have been applied

2020-10-04 17:12 UTC, pyronaur commented
I checked out the PR to give it a spin. Code-wise this looks good, but I think we need to brainstorm a bit about how it looks on the website. 

I took a few screenshots in various themes:

![Screen Shot 2020-10-04 at 7 58 09 PM](https://user-images.githubusercontent.com/988095/95021849-3cc22580-067c-11eb-8c0a-a8bb30dd7da4.png)
![Screen Shot 2020-10-04 at 7 58 22 PM](https://user-images.githubusercontent.com/988095/95021850-3e8be900-067c-11eb-9ba1-6478e7ed8d97.png)
![Screen Shot 2020-10-04 at 7 58 36 PM](https://user-images.githubusercontent.com/988095/95021852-3fbd1600-067c-11eb-98c2-552ea7553a14.png)
![Screen Shot 2020-10-04 at 7 56 26 PM](https://user-images.githubusercontent.com/988095/95021853-40ee4300-067c-11eb-8660-32fc5ce3a6a4.png)
![Screen Shot 2020-10-04 at 7 56 09 PM](https://user-images.githubusercontent.com/988095/95021854-42b80680-067c-11eb-9ee2-c81b617507b4.png)


2 things stand out to me:

1) There's no indication on which category I currently have open, which might be a bit confusing

2) In some layouts, the page appears slightly broken. We probably can't make it beautiful in every theme, but I think we can try at least making it passable in most. Perhaps add some spacing?

Not sure what's a good approach here. I tried adding a `button` class to the elements, and with a little bit of CSS we can center-align them, like so:

![Screen Shot 2020-10-04 at 8 09 34 PM](https://user-images.githubusercontent.com/988095/95022087-a2fb7800-067d-11eb-83cc-3541b6c08a2b.png)

But I'm not sure how that'll work

2023-12-05 14:32 UTC, closed without merging